apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  #persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/jairo/Keptn-k3s/wordpress/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
