apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
    tier: frontend
spec:
  selector:
    app: wordpress
    tier: frontend
  ports:
    - name: http-sv-port
      port: 80
      targetPort: http-port
#    - name: https-sv-port
 #     port: 443
  #    targetPort: https-port
  type: NodePort
