apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: wordpress
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: database
  template:
    metadata:
      labels:
        app: wordpress
        tier: database
    spec:
      containers:
        - name: mysql
          image: mariadb:latest
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
              name: db-port
          env:
            - name: MARIADB_USER
              valueFrom:
                configMapKeyRef:
                  name: wpdates
                  key: bd_user
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: wpdates
                  key: bd_name
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wppass
                  key: bd_password
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wppass
                  key: bd_rootpassword
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
